//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brewery.Web.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Brewery.Web.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Arabe
        ///        .
        /// </summary>
        internal static string HeaderAr {
            get {
                return ResourceManager.GetString("HeaderAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Brasseur
        ///        .
        /// </summary>
        internal static string HeaderBrewery {
            get {
                return ResourceManager.GetString("HeaderBrewery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Anglais
        ///        .
        /// </summary>
        internal static string HeaderEn {
            get {
                return ResourceManager.GetString("HeaderEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Français
        ///        .
        /// </summary>
        internal static string HeaderFr {
            get {
                return ResourceManager.GetString("HeaderFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Accueil
        ///        .
        /// </summary>
        internal static string HeaderHome {
            get {
                return ResourceManager.GetString("HeaderHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Connexion
        ///        .
        /// </summary>
        internal static string HeaderLogin {
            get {
                return ResourceManager.GetString("HeaderLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Déconnexion
        ///        .
        /// </summary>
        internal static string HeaderLogout {
            get {
                return ResourceManager.GetString("HeaderLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Créer un compte
        ///        .
        /// </summary>
        internal static string HeaderNewUser {
            get {
                return ResourceManager.GetString("HeaderNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Néerlandais
        ///        .
        /// </summary>
        internal static string HeaderNl {
            get {
                return ResourceManager.GetString("HeaderNl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Grossiste
        ///        .
        /// </summary>
        internal static string HeaderWholesaler {
            get {
                return ResourceManager.GetString("HeaderWholesaler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Chargement...
        ///        .
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            G-brewery, votre brasseur en ligne !
        ///        .
        /// </summary>
        internal static string Text1 {
            get {
                return ResourceManager.GetString("Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Pour chaque bière étrangère, nous fournissons de multiples informations, sur la contenance, le pays d’origine, le degré d’alcool, le style et les divers arômes.
        ///        .
        /// </summary>
        internal static string Text10 {
            get {
                return ResourceManager.GetString("Text10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Enfin, le paiement est totalement sécurisé. Et vous bénéficierez d’une expédition rapide (dans les 24 heures).
        ///        .
        /// </summary>
        internal static string Text11 {
            get {
                return ResourceManager.GetString("Text11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Une question au sujet de notre offre de boissons ? Vous souhaitez en savoir plus au sujet de la vente en gros de bières ? N’hésitez pas à nous joindre par email. Vous poserez toutes vos questions ou nous téléphonerez pour échanger avec des spécialistes de cette boisson !
        ///        .
        /// </summary>
        internal static string Text12 {
            get {
                return ResourceManager.GetString("Text12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Dans la même catégorie
        ///        .
        /// </summary>
        internal static string Text13 {
            get {
                return ResourceManager.GetString("Text13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Comment fonctionne G-brewery ?
        ///        .
        /// </summary>
        internal static string Text14 {
            get {
                return ResourceManager.GetString("Text14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            La tireuse à bière G-brewery est un chef d&apos;œuvre de technologie ! Outre ses nombreuses fonctionnalités vous offrant une expérience dégustation sans pareil, la machine PerfectDraft Pro a surtout la faculté d’être une tireuse connectée. Contrôlable grâce à l’application...
        ///        .
        /// </summary>
        internal static string Text15 {
            get {
                return ResourceManager.GetString("Text15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Faites découvrir la bière IPA grâce au brasseur en ligne G-brewery !
        ///        .
        /// </summary>
        internal static string Text16 {
            get {
                return ResourceManager.GetString("Text16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Restaurateur ou cafetier ? Caviste ou responsable du rayon Alcools d’une grande surface alimentaire ? Vous souhaitez diversifier votre offre en proposant des bières fortes en houblon ? Vous apprécierez l’offre disponible chez G-brewery et les multiples avantages de ce grossiste spécialisé ! Une grande variété de...
        ///        .
        /// </summary>
        internal static string Text17 {
            get {
                return ResourceManager.GetString("Text17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Vous souhaitez varier votre offre en alcools ? Cafetier, restaurateur ou caviste, vous désirez fidéliser ou attirer une nouvelle clientèle avec des bières étrangères ? Grâce à G-brewery, vous trouverez votre bonheur ! Profitez d’un large choix et de multiples services en commandant sur notre site !
        ///        .
        /// </summary>
        internal static string Text2 {
            get {
                return ResourceManager.GetString("Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Pourquoi privilégier l’achat d’une bière en ligne sur G-brewery ?
        ///        .
        /// </summary>
        internal static string Text3 {
            get {
                return ResourceManager.GetString("Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Depuis 2007, nous commercialisons auprès des particuliers et des professionnels ces boissons. En nous adressant aux grandes surfaces, aux gérants de cafés, aux restaurants et aux hôtels, nous avons développé une expertise, précieuse pour bien comprendre les attentes de tous les amateurs de bières.
        ///        .
        /// </summary>
        internal static string Text4 {
            get {
                return ResourceManager.GetString("Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Ainsi, pour étancher la soif de découverte de vos clients, notre offre comporte des boissons de la plupart des continents. L’Europe bien entendu où les plus grandes nations brassicoles sont représentées. Cependant, outre l’Allemagne, la Belgique, le Royaume-Uni ou les Pays-Bas, d’autres pays figurent dans notre catalogue. Citons notamment l’Autriche, le Danemark, la Suède, l’Italie ou le Portugal. Nous n’avons pas oublié les Amériques. Ainsi, vous servirez à vos clients habitués ou de passage  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Text5 {
            get {
                return ResourceManager.GetString("Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Ces bouteilles sont disponibles sous diverses contenances. Elles proviennent généralement de brasseries artisanales. Ainsi, vous ferez découvrir à vos clients des goûts souvent insolites. Vous les ferez voyager en leur faisant goûter de nouveaux arômes !
        ///        .
        /// </summary>
        internal static string Text6 {
            get {
                return ResourceManager.GetString("Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Cependant, nous n’avons pas oublié les grandes brasseries belges et allemandes. Pour certaines d’entre-elles, des fûts sont disponibles, pour un service à la pression !
        ///        .
        /// </summary>
        internal static string Text7 {
            get {
                return ResourceManager.GetString("Text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Quels sont les services G-brewery ?
        ///        .
        /// </summary>
        internal static string Text8 {
            get {
                return ResourceManager.GetString("Text8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Vous ne connaissez pas très bien les divers types de bières ? Vous ne savez pas quelle référence proposer pour un repas dans votre restaurant ? En commandant sur notre boutique en ligne, vous profiterez de notre expertise.
        ///        .
        /// </summary>
        internal static string Text9 {
            get {
                return ResourceManager.GetString("Text9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Brasseur en ligne
        ///        .
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
